# Jinx Custom Theme for Superfile
# Created for a transparent background with custom colors

# Code syntax highlight theme (use "catppuccin-mocha" or any Chroma theme)
code_syntax_highlight = "catppuccin-mocha"

# ========= Border Colors =========
file_panel_border = "#FD77DD"  # Neon Blue
sidebar_border = "#FD77DD"  # Magenta
footer_border = "#A9DD48"  # Toxic Green

# ========= Active Border Colors =========
file_panel_border_active = "#FD77DD"  # Light Pink
sidebar_border_active = "#FD77DD"  # Neon Blue
footer_border_active = "#A6E3A1"  # Soft Green
modal_border_active = "#FD77DD"  # Magenta

# ========= Foreground (Text) =========
full_screen_fg = "#FDEEFC"  # Light Pink
file_panel_fg = "#FDEEFC"
sidebar_fg = "#FDEEFC"
footer_fg = "#FDEEFC"
modal_fg = "#FDEEFC"

# ========= Special Colors =========
cursor = "#FD77DD"  # Magenta (Jinx Highlight)
correct = "#A9DD48"  # Toxic Green
error = "#f38ba8"  # Error Red
hint = "#54C1DB"  # Neon Blue
cancel = "#eba0ac"  # Soft Red
gradient_color = ["#FD77DD", "#54C1DB"]  # Magenta to Neon Blue Gradient

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#A9DD48"  # Toxic Green
file_panel_top_path = "#54C1DB"  # Neon Blue
file_panel_item_selected_fg = "#FDEEFC"  # Light Pink
file_panel_item_selected_bg = "transparent"

# ========= Sidebar Special Items =========
sidebar_title = "#54C1DB"  # Neon Blue
sidebar_item_selected_fg = "#FDEEFC"  # Light Pink
sidebar_item_selected_bg = "transparent"
sidebar_divider = "#FD77DD"  # Magenta

# ========= Modal Special Items =========
modal_cancel_fg = "#FDEEFC"  # Light Pink
modal_cancel_bg = "#FD77DD"  # Magenta

modal_confirm_fg = "#383838"
modal_confirm_bg = "#54C1DB"  # Neon Blue

# ========= Help Menu =========
help_menu_hotkey = "#FD77DD"  # Magenta
help_menu_title = "#54C1DB"  # Neon Blue
