Error: no such file. (`/Users/yutakirihara/.config/nvim/ftplugin/java.lua
/Users/yutakirihara/.config/nvim/ftplugin/html.lua
/Users/yutakirihara/.config/nvim/init.lua
/Users/yutakirihara/.config/nvim/lua/core/autocmds.lua
/Users/yutakirihara/.config/nvim/lua/core/keybinds.lua
/Users/yutakirihara/.config/nvim/lua/core/snacks-keybinds.lua
/Users/yutakirihara/.config/nvim/lua/core/options.lua
/Users/yutakirihara/.config/nvim/lua/plugins/palette.lua
/Users/yutakirihara/.config/nvim/lua/plugins/noice.lua
/Users/yutakirihara/.config/nvim/lua/plugins/dap-virtualtext.lua
/Users/yutakirihara/.config/nvim/lua/plugins/luarocks.lua
/Users/yutakirihara/.config/nvim/lua/plugins/emmet.lua
/Users/yutakirihara/.config/nvim/lua/plugins/flash.lua
/Users/yutakirihara/.config/nvim/lua/plugins/fzf.lua
/Users/yutakirihara/.config/nvim/lua/plugins/clang-extensions.lua
/Users/yutakirihara/.config/nvim/lua/plugins/surround-vim.lua
/Users/yutakirihara/.config/nvim/lua/plugins/modicator.lua
/Users/yutakirihara/.config/nvim/lua/plugins/dap-ui.lua
/Users/yutakirihara/.config/nvim/lua/plugins/neoscroll.lua
/Users/yutakirihara/.config/nvim/lua/plugins/lspconfig.lua
/Users/yutakirihara/.config/nvim/lua/plugins/rest-nvim.lua
/Users/yutakirihara/.config/nvim/lua/plugins/tiny-devicons-auto.lua
/Users/yutakirihara/.config/nvim/lua/plugins/trouble.lua
/Users/yutakirihara/.config/nvim/lua/plugins/highlight-colors.lua
/Users/yutakirihara/.config/nvim/lua/plugins/dooing.lua
/Users/yutakirihara/.config/nvim/lua/plugins/markdown-preview.lua
/Users/yutakirihara/.config/nvim/lua/plugins/smear-cursor.lua
/Users/yutakirihara/.config/nvim/lua/plugins/tmux-navigator.lua
/Users/yutakirihara/.config/nvim/lua/plugins/yanky.lua
/Users/yutakirihara/.config/nvim/lua/plugins/none-ls.lua
/Users/yutakirihara/.config/nvim/lua/plugins/web-devicons.lua
/Users/yutakirihara/.config/nvim/lua/plugins/gitsigns.lua
/Users/yutakirihara/.config/nvim/lua/plugins/persistence.lua
/Users/yutakirihara/.config/nvim/lua/plugins/subsitute.lua
/Users/yutakirihara/.config/nvim/lua/plugins/snacks.lua
/Users/yutakirihara/.config/nvim/lua/plugins/mini.lua
/Users/yutakirihara/.config/nvim/lua/plugins/jdtls.lua
/Users/yutakirihara/.config/nvim/lua/plugins/which-key.lua
/Users/yutakirihara/.config/nvim/lua/plugins/completions-blink.lua
/Users/yutakirihara/.config/nvim/lua/plugins/treesitter.lua
/Users/yutakirihara/.config/nvim/lua/plugins/maven.lua
/Users/yutakirihara/.config/nvim/lua/plugins/dap.lua
/Users/yutakirihara/.config/nvim/lua/plugins/toggleterm.lua
/Users/yutakirihara/.config/nvim/lua/plugins/transparent.lua
/Users/yutakirihara/.config/nvim/lua/plugins/harpoon.lua
/Users/yutakirihara/.config/nvim/lua/plugins/render-markdown.lua
/Users/yutakirihara/.config/nvim/lua/plugins/telescope-spectre.lua
/Users/yutakirihara/.config/nvim/lua/plugins/mason.lua
/Users/yutakirihara/.config/nvim/retired/colorscheme.lua
/Users/yutakirihara/.config/nvim/retired/completions.lua`)
