# Superfile Configuration

# Theme Configuration
theme = "jinx"

# File & Directory Management
editor = "nvim"  # Open files in Neovim
dir_editor = ""  # Open directories in Neovim

# Behavior Settings
auto_check_update = true  # Enable automatic update checks
cd_on_quit = true  # Change terminal directory when quitting
default_open_file_preview = true  # Show file preview by default
default_directory = "."

# File Sorting Options
default_sort_type = 0  # 0 = Name, 1 = Size, 2 = Date Modified
sort_order_reversed = false  # Ascending order
case_sensitive_sort = false  # Case-insensitive sorting

# Debugging
debug = false  # Set to true for detailed logs

# UI/Style Preferences
nerdfont = true  # Enable Nerd Font icons
transparent_background = true # Disable transparency
file_preview_width = 3  # File preview takes 1/3 of the terminal width
sidebar_width = 20  # Sidebar width

# Border Styling (Minimal Rounded Corners)
border_top = "─"
border_bottom = "─"
border_left = "│"
border_right = "│"
border_top_left = "╭"
border_top_right = "╮"
border_bottom_left = "╰"
border_bottom_right = "╯"
border_middle_left = "├"
border_middle_right = "┤"

# Metadata & Plugins
metadata = false  # Disable metadata extraction (requires exiftool)
enable_md5_checksum = false  # Disable MD5 checksum generation
file_size_use_si = false
